### ISSUE TITLE
Updated user guide introduction for nmigen.

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen#24]
<a href="https://github.com/sam-falvo"><img src="https://avatars0.githubusercontent.com/u/1495032?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sam-falvo](https://github.com/sam-falvo)**
_Sunday Jan 06, 2019 at 20:02 GMT_
_Originally opened as https://github.com/m-labs/nmigen/pull/22_

----

The goal is to work through each section, one by one, receiving documentation reviews along the way.  The introduction is a good first step.  Feedback appreciated!

----

_**[sam-falvo](https://github.com/sam-falvo)** included the following code: https://github.com/m-labs/nmigen/pull/22/commits_

**Comment by whitequark** [comment]
@sam-falvo Thank you for your effort. Ultimately I decided to completely rewrite the manual for nMigen, with both different style and end goals. The current (quite unfinished but already useful) manual is available at https://nmigen.info/nmigen/.

@eilims You might find the new installation page useful: https://nmigen.info/nmigen/latest/install.html
