### ISSUE TITLE
Reliable installation on Windows

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen#244]
<a href="https://github.com/whitequark"><img src="https://avatars1.githubusercontent.com/u/54771?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [whitequark](https://github.com/whitequark)**
_Thursday Oct 03, 2019 at 09:54 GMT_
_Originally opened as https://github.com/m-labs/nmigen/issues/244_

----

This is apparently [a problem](https://github.com/m-labs/nmigen/issues/242#issuecomment-537295898).

**Comment by whitequark** [comment]
Fixed in 126f0be731ab008657ca1c4fc05ce7cc6e355169 and https://nmigen.info/nmigen/latest/install.html.
