### ISSUE TITLE
pysim2 doesn't write input signals to VCD

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen#280]
<a href="https://github.com/adamgreig"><img src="https://avatars2.githubusercontent.com/u/47219?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adamgreig](https://github.com/adamgreig)**
_Wednesday Dec 04, 2019 at 12:23 GMT_
_Originally opened as https://github.com/m-labs/nmigen/issues/280_

----

Since updating to pysim2, any signals not driven from inside the fragment being simulated are not written to the VCD. This means signals which are inputs to the fragment and are driven by a sync process added to the simulator do not show up.

I think this is because FragmentCompiler is the only thing that adds signals to `signal_names`, but it is only called for the fragment the simulator is created with, not for any processes that are then added to the simulator. I might be misunderstanding the code though.

Additionally, as far as I can tell the `traces` argument to `write_vcd` is totally unused: it gets passed to `_VCDWaveformWriter.__init__`, which does nothing with it.

**Comment by whitequark** [comment]
@adamgreig I fixed both issues you've reported. I'm sorry that such a critical issue ended up being open for so long.

**Comment by adamgreig** [comment]
Thank you!
