### ISSUE TITLE
vendor.xilinx_7series: Vivado TIMING-2 Warning

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen#301]
<a href="https://github.com/peteut"><img src="https://avatars3.githubusercontent.com/u/1288741?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peteut](https://github.com/peteut)**
_Wednesday Jan 08, 2020 at 19:35 GMT_
_Originally opened as https://github.com/m-labs/nmigen/issues/301_

----

*Vivado* issues TIMING-2 (default severity: CRITICAL) when `create_clock` uses a signal. 
Here is a potential solution to please `create_clock`: https://github.com/peteut/nmigen/commit/9e79a30655123c02a2a3025d8f5af0ce8c076b7f .

**Comment by whitequark** [comment]
@peteut Thank you for bringing this to my attention; I did not realize that the exact placement of the constraint is semantically important. I've added `report_methodology` to the Vivado scripts, and I've changed the core APIs so that the constraint can be appropriately placed without any ugliness.

**Comment by peteut** [comment]
> @peteut Thank you for bringing this to my attention; I did not realize that the exact placement of the constraint is semantically important. I've added `report_methodology` to the Vivado scripts, and I've changed the core APIs so that the constraint can be appropriately placed without any ugliness.

@whitequark Thanks, much nicer indeed!
