### ISSUE TITLE
vendor.lattice_ecp5: Support internal oscillator (OSCG)

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen#306]
<a href="https://github.com/miek"><img src="https://avatars3.githubusercontent.com/u/578095?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [miek](https://github.com/miek)**
_Friday Jan 17, 2020 at 17:06 GMT_
_Originally opened as https://github.com/m-labs/nmigen/pull/306_

----

----

_**[miek](https://github.com/miek)** included the following code: https://github.com/m-labs/nmigen/pull/306/commits_

**Comment by whitequark** [comment]
Merged with minor stylistic modifications.
