### ISSUE TITLE
build.dsl: allow strings to be used as connector numbers

### ISSUE THREAD

**Issue by nmigen-issue-migration** [nmigen/nmigen#313]
<a href="https://github.com/anuejn"><img src="https://avatars2.githubusercontent.com/u/8377902?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anuejn](https://github.com/anuejn)**
_Sunday Jan 26, 2020 at 17:37 GMT_
_Originally opened as https://github.com/m-labs/nmigen/pull/313_

----

follow up of #311 .
Is it as simple as that or did I miss something?

----

_**[anuejn](https://github.com/anuejn)** included the following code: https://github.com/m-labs/nmigen/pull/313/commits_

**Comment by whitequark** [comment]
@anuejn Merged, with slight modifications: I reworded the error messages, and added tests.
