### ISSUE TITLE
FSM with transition to nonexistent state should not elaborate

### ISSUE THREAD

**Issue by awygle** [nmigen/nmigen#315]
M(ish)CVE: https://gist.github.com/awygle/00cca56b2d58185f3ab7112739588882

Basically, if you have an FSM transition to a state which doesn't have a corresponding with m.State("NAME") statement, I'd expect it to fail to elaborate.

I'm admittedly very new to nmigen so it's possible I am doing something wrong here, but this seems sufficiently intuitive that even if it's not the intended behavior, I'd argue that perhaps it ought to be.

**Comment by whitequark** [comment]
It's a bit of an edge case; in Migen, this construct would fail to synthesize correctly (!), IIRC the offending edge would just act as if it does not exist. In nMigen this implicitly creates a state, but I agree this might not be desirable.
