### ISSUE TITLE
Case pattern syntax improvement

### ISSUE THREAD

**Issue by porglezomp** [nmigen/nmigen#316]
While I was working with cases I tried using underscores in my patterns as byte separators, expecting it to match the integer literal syntax, but it was rejected.

I'd like to be able to write patterns like `"0001_0---"`—does this seem like a good idea, or is the potential confusion between `-` and `_` a problem?

**Comment by whitequark** [comment]
I think the potential confusion is a problem. Since we don't need it to be a single lexical token (like Python does), what about just using spaces?

**Comment by porglezomp** [comment]
I would also be happy with spaces as the separator.
