### ISSUE TITLE
Probable submodule name collision breaking modularity

### ISSUE THREAD

**Issue by galibert** [nmigen/nmigen#331]
I may have missed something, but...

Imagine you create a module of type M68000.  It has a submodule of type BusAccess.  To get a meaningful name in the rtlil and every tool that uses it, it is created in the recommended way in elaborate:
- m.submodules.busaccess = busaccess = BusAccess()

Then the name "busaccess" is used, which is good.  But it seems that module names must be unique in the whole system.  So does that mean one couldn't have two instances of M68000 in the same system if we want significant names?

**Comment by whitequark** [comment]
It doesn't need to be unique in the entire design; it only needs to be unique within a single parent module.

**Comment by galibert** [comment]
Ok, I can confirm nmigen automatically renames the colliding names (with a $number suffix) to avoid collisions, very nice.
