### ISSUE TITLE
Allow selecting proof engine in FHDLTestCase

### ISSUE THREAD

**Issue by awygle** [nmigen/nmigen#376]
Assuming that `FHDLTestCase` is intended to be used by the general public, it would be convenient to be able to specify the proof engine to use. `abc pdr`, for example, can solve certain proofs that fail k-induction.

**Comment by whitequark** [comment]
It is absolutely *not* intended to be a public API, just like anything else in `nmigen.test`. Just another confusing Python convention where tests end up a part of the main package.
