### ISSUE TITLE
UnusedMustUse warnings are emitted after the toolchain ran

### ISSUE THREAD

**Issue by anuejn** [nmigen/nmigen#383]
The UnusedMustUse warnings rely on the garbage-collector and are therefore are emitted at the termination of the python script. This is quite unfortunate when one is using nmigen to execute the build plan because one has to wait for the (long-running) toolchain to finish before obvious bugs are pointed out.

**Comment by whitequark** [comment]
I'm not aware of any way to improve on this in general; in Migen you didn't even have late warnings, you were just left to wonder why your design is broken.

If you find that you stumble on this often, use `do_build=False`.

**Comment by anuejn** [comment]
Ok thanks anyways :)
