### ISSUE TITLE
Adding Shapes gives counterintuitive results

### ISSUE THREAD

**Issue by awygle** [nmigen/nmigen#421]
`Shape`s implement `__add__`, but adding them is currently not useful:

```python
>>> from nmigen import *
>>> x = Signal(16)
>>> y = Signal(32)
>>> s = x.shape() + y.shape()
>>> s
(16, False, 32, False)
```

The expected result here (I argue) would be `(48, False)`, but (probably because `Shape` is a named tuple under the hood) we get the not-very-useful result shown above.

Obviously in this case you can do `(x+y).shape()` but that's not always easy or possible (I hit a particular case involving an `Enum`)

**Comment by whitequark** [comment]
So there are two unrelated issues here. First, that currently you can do `shape + shape` and the result is never desirable. We should fix that by not using `namedtuple` while still allowing to destructure shapes using `width, signed = shape`. (Is that possible? I think we can override `__iter__` to do it...)

Second, the idea of overloading the `+` operation on shapes to do something not really related to addition. It doesn't seem like a good idea to me, but we can discuss it in a different issue.

**Comment by awygle** [comment]
I agree it's a bad idea. We should stop implementing extraneous operators for `Shape`, and that's all.

**Comment by awygle** [comment]
Should we preserve comparing `Shape`s to tuples of `(int, bool)`? This currently works (and is used in the test suite) but feels like a bit of a footgun.

**Comment by whitequark** [comment]
> This currently works (and is used in the test suite)

Where?

**Comment by whitequark** [comment]
Oh sorry, you mean comparing *for equality*, not for ordering. Yeah let's preserve that, we can always deprecate it later if it turns out to cause issues.
