### ISSUE TITLE
Inconsistency between a parameter name for AsyncFFSynchronizer and FFSynchronizer

### ISSUE THREAD

**Issue by ECP5-PCIe** [nmigen/nmigen#467]
The output domain parameter is `o_domain` for the synchronous one and `domain` for the asynchronous one

**Comment by awygle** [comment]
Since we haven't had a release since this was added, can I just fix this, or do I have to handle backwards-compat?

**Comment by whitequark** [comment]
We can just fix this.

**Comment by whitequark** [comment]
(But do we want to have `o_domain` everywhere rather than `domain` everywhere? I'm not sure...)

**Comment by awygle** [comment]
Agreed about the uncertainty but we can talk about that at some eventual meeting.

**Comment by whitequark** [comment]
We decided to use `o_domain` for `AsyncFFSynchronizer` on the meeting.
