### ISSUE TITLE
wrong documentation for word_select

### ISSUE THREAD

**Issue by DaKnig** [nmigen/nmigen#474]
from the language guide:
> `nMigen operation      | Equivalent Python code`
> `a.word_select(b, i) | a[b*i:b*i+i]`

I think that should actually be `a[b*i:b*(i+1)]`

**Comment by whitequark** [comment]
Hm, no; the documentation is technically correct. However, the variable names are confusing, since `i` isn't an index (in fact it is a width). Confusing docs are still a bug though so I'll fix that.
