### ISSUE TITLE
Emit a warning when no clock is set

### ISSUE THREAD

**Issue by pepijndevos** [nmigen/nmigen#475]
I was copy-pasting from various tutorials and examples, and managed to set up pysim without a clock. This caused `Tick()` to never return. Example snippet

```python
sim = Simulator(spr)
def testbench():
    yield Tick()

#sim.add_clock(1e-6)
sim.add_process(testbench)
sim.run()
```

The reason I missed this was a combination of the tutorial I was looking at using `comb` and `Delay()` and the example I was looking at using an opaque `main()` function that sets up the simulator internally.

**Comment by pepijndevos** [comment]
I think I found the previous issue you were referring to #442

**Comment by whitequark** [comment]
Ah right
