### ISSUE TITLE
Explicit deprecation/removal notice for FHDLTestCase

### ISSUE THREAD

**Issue by BracketMaster** [nmigen/nmigen#484]
FHDLTestCase is no longer accessible in nMigen 0.3.
An attempt to import it should still fail, but let the user
know FHDLTestCase was intentionally removed.

Perhaps something to the effect of
```
Removal Notice: FHDLTestCase has been removed as per https://github.com/nmigen/nmigen/pull/399#issuecomment-638514027
```

Maybe ``Removal Notice`` could be highlighted in red?

**Comment by awygle** [comment]
I think this is a good idea, and I also think it highlights that (given you clearly don't like `FHDLTestCase`, whitequark) we should prioritize designing its replacement (if any? not sure what your long-term plans are here). I know I'm using (a local fork of) `FHDLTestCase` in all of my nmigen designs, and most people I talk to are excited to use formal tooling with nmigen. This issue isn't the right place to track that of course so we should file a separate one if we don't have it already...

**Comment by whitequark** [comment]
> given you clearly don't like `FHDLTestCase`,

It's not that I don't like it in particular. It's more that it was always intended as an internal API, and absolutely no thought went into its design. I assumed, wrongly, that people would know better than to dig out random stuff from the `test/` subfolder...

> we should prioritize designing its replacement

Sure.
