### ISSUE TITLE
nMigen doesn't like clock domains with underscores

### ISSUE THREAD

**Issue by DaKnig** [nmigen/nmigen#489]
as the title suggests; the MCVE errors out with `Domain 'cd_40' is used but not defined` but changing all occurrences of `cd_40` to `cd40` fixes the issue.
 
MCVE:
https://paste.debian.net/1161171/

**Comment by whitequark** [comment]
This is a feature: https://github.com/nmigen/nmigen/blob/630c0fd99af6cf52d14c4b57067933d7c96cdf86/nmigen/hdl/cd.py#L15-L19

So if you assign a domain to `cd_40` the domain itself will be named just `"40"`.
