### ISSUE TITLE
Elif without If not recognized in nested If

### ISSUE THREAD

**Issue by tpwrules** [nmigen/nmigen#500]
The following code snippet does not produce a syntax error and in fact generates without any complaints at all (not sure what the effect is):
```python
s = Signal()
with m.If(1):
    with m.Elif(2):
        m.d.comb += s.eq(3)
```

I would expect it to raise `nmigen.hdl.dsl.SyntaxError: Elif without preceding If` like the following snippet does:
```python
s = Signal()
with m.Elif(4):
    m.d.comb += s.eq(5)
```

**Comment by whitequark** [comment]
The effect is this:
```
(switch
  (cat (sig b) (sig a))
   (case -1 (eq (sig s) (const 1'd1)))
   (case 1- ))
```
so basically (converting back to the notation in your example):
```python
with m.If(2):
    m.d.comb += s.eq(3)
```
which is pretty weird indeed.
