### ISSUE TITLE
Provide public api to add build commands

### ISSUE THREAD

**Issue by anuejn** [nmigen/nmigen#515]
It would be nice to have (semi) public API to inject custom build commands into the build_name.{sh,bat} files.
My specific use case is to generate a bash script that contains a base64 encoded version of the bit stream that loads the bit stream automatically via the linux fpgamanager infrastructrure  on a zynq. 
Currently, I am having [quite a hack in place](https://github.com/apertus-open-source-cinema/nmigen-gateware/blob/master/src/soc/soc_platform.py#L31) to implement that but that constantly breaks and is a very bad solution.

For me live would be easier if `TemplatedPlatform` had an extra_command_templates property that is guaranteed to be not a property object and therefore easy to override.

**Comment by whitequark** [comment]
> My specific use case is to generate a bash script that contains a base64 encoded version of the bit stream that loads the bit stream automatically via the linux fpgamanager infrastructrure on a zynq.

This sounds like it should be a part of an external programmer. Could you explain that workflow in a bit more detail?

**Comment by anuejn** [comment]
At first that logic was inside the `toolchain_program()` function of the platform but I realized that I want that bash script to be generated for later use even if I do not program the FPGA directly. I see that file a bit more like what a svf file is compared to the normal bitstream format.

**Comment by whitequark** [comment]
Ack, that makes sense. I'll see what can be done.

**Comment by anuejn** [comment]
My workflow involves generating that file (which also contains other stuff from the design like a memorymap).
This file is then copied over to the zynq via scp and executed via ssh in the `toolchain_program()` function.

**Comment by anuejn** [comment]
:+1:

**Comment by anuejn** [comment]
see #618. Not needed.
