### ISSUE TITLE
Unusual Display Behaviors

### ISSUE THREAD

**Issue by BracketMaster** [nmigen/nmigen#583]
Sometimes display will trigger twice(when it should trigger once) or once(when
it should trigger twice).

Below, I present a case where display should fire twice in state two:

```python3
from nmigen import Module, Display, Signal

m = Module()

sig = Signal()

with m.FSM(name="simple"):
    with m.State("one"):
        m.d.comb += Display("one")
        m.next = "two"
    with m.State("two"):
        m.d.comb += Display("two")
        m.next = "two"

from nmigen.sim import Simulator, Tick

sim = Simulator(m)
sim.add_clock(1e-6)

def process():
    yield Tick()

sim.add_sync_process(process)
sim.run()

```

evaluating this produces:

```bash
$ python3 test.py
one
two
```

where we expect:

```bash
$ python3 test.py
one
two
two
```

A counterexample:

By changing the following

```python3
    with m.State("two"):
        m.d.comb += Display("two")
        m.next = "two"
```

to 

```python3
    with m.State("two"):
        m.d.comb += Display("two")
        m.next = "one"
```

we observe in the expected behavior of

```bash
$ python3 test.py
one
two
one
```

**Comment by BracketMaster** [comment]
after further investigation, it seems that using Display within sync is more reliable

**Comment by whitequark** [comment]
This is generally expected behavior for comb Display.

**Comment by BracketMaster** [comment]
Alright. I think I agree.

**Comment by whitequark** [comment]
Once there is a sink for `Display`-produced events I think you will be able to post-process them to make sure only one fires during a given simulation time instant.
