### ISSUE TITLE
Using nMigen with YoWASP in Windows

### ISSUE THREAD

**Issue by fnsangiul** [nmigen/nmigen#642]
Hello, I'm having an issue trying to run the Blinky example with the icestick board. I installed nmigen (not nmigen-yosys), nmigen-boards, yowasp-yosys and yowasp-nextpnr-ice40 in Windows 10. When I try to program the board I get the following error

nmigen._toolchain.ToolNotFound: Could not find required tool yosys in PATH. Place it directly in PATH or specify path explicitly via the YOSYS environment variable

I understand that the toolchain for the ice40 has to be installed separately and the environment variables defined, however I can't make it work. How do I link the toolchain installed with YoWASP in Windows? Please excuse me if I'm not describing my issue properly.

Thank you

**Comment by whitequark** [comment]
Before running nMigen, use:
```
set YOSYS=yowasp-yosys
set NEXTPNR_ICE40=yowasp-nextpnr-ice40
set ICEPACK=yowasp-icepack
```

**Comment by fnsangiul** [comment]
Thank you! It worked
