### ISSUE TITLE
VCDWriter.register_alias() called in pysim.py:110 does not exist

### ISSUE THREAD

**Issue by hansfbaier** [nmigen/nmigen#645]
steps to reproduce:
```bash
git clone https://github.com/hansfbaier/nmigen-library/
cd nmigen-library
export PYTHONPATH='.'
export GENERATE_VCDS=1
python3 -m unittest nmigen_library.io.ws2812.WS2812Test
```

**Comment by rroohhh** [comment]
Are you sure you are satisfying the requirements of `nmigen`? The `register_alias` method was added in `pyvcd` versi.on `0.2.2`, do you have a older one installed by any chance?

**Comment by hansfbaier** [comment]
@rroohhh Ahh, yes, sorry my bad, I thought for some weird reason (lack of sleep, probably) that VCDWriter was part of nmigen.
